### ISSUE TITLE
Use train/val/test data for the encoding to prevent not seen classes

### ISSUE THREAD

**Issue by franchuterivera** [LMZimmer/Auto-PyTorch_refactor#12]
This line only uses the training data to build an encoding space:
https://github.com/LMZimmer/Auto-PyTorch_refactor/blob/720bde8d873a272c5a29ddb2fd742a7affdcbd71/autoPyTorch/pipeline/components/preprocessing/encoding/OrdinalEncoder.py#L25

To prevent issues, employ train, test, val data IF available to build and fit encoders.

**Comment by ravinkohli** [comment]
I think this issue can be closed.
