### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by ArlindKadra** [LMZimmer/Auto-PyTorch_refactor#31]
https://github.com/LMZimmer/Auto-PyTorch_refactor/blob/0cee2749196e1b04a298b0e7f1357c7863326ffc/autoPyTorch/pipeline/tabular_classification.py#L98-L108

In my opinion, it should be mentioned here that this actually fits the pipeline and trains the model. 
Also, the naming is pretty close to the `predict` method of the `base_pipeline.py` module and confuses as to which method does what. On an initial glance it seems like they both just predict, without accounting for the memory error note at the doc.

**Comment by ArlindKadra** [comment]
On another glance, this does not feature `Y_train`. So this is does not fit the pipeline.

**Comment by LMZimmer** [comment]
`predict_proba` is unique to classification settings, that is why it is handled in the child classes of `BasePipeline`
