### ISSUE TITLE
List the metrics in the __init__.py

### ISSUE THREAD

**Issue by franchuterivera** [LMZimmer/Auto-PyTorch_refactor#38]
I will be pretty cool if we can do something like:

```
from autoPyTorch.metrics import  Accuracy, etc..
```

As of now the metrics are defined individually, like in autoPyTorch/pipeline/components/training/metrics/__init__.py

The above is useful for the end-user and for unit testing

**Comment by ravinkohli** [comment]
This can be done now, as all the metrics have been defined in autoPyTorch.metrics.metrics. Is it fine? or should I make them available from autoPyTorch.metrics?

**Comment by franchuterivera** [comment]
This has been addressed in #52
